sudo: required

language: ruby

rvm:
  - 2.6.4
  - jruby
  - truffleruby

cache:
  bundler: true

addons:
  code_climate:
    repo_token: 6d1107ed298902217e9ba186b3d717461f190e8c783e6561095d45d01864470a
  postgresql: "12.0"

before_install:
  - gem install bundler

before_script:
  - cp .rspec.travis .rspec
  - cp config/database.yml.travis config/database.yml
  - psql --command='CREATE DATABASE travis_ci_test;' --username=postgres
  - bundle exec rake db:schema:load RAILS_ENV=test
  - bundle exec rake db:create db:migrate RAILS_ENV=test
